name: Test web
on:
<<<<<<< HEAD
    push:
        branches:
            - "**"
        inputs:
            test_script:
                default: "Bai22.Bai22_DatePickerTest"
            env:
                default: "staging"
=======
    # push:
    #     branches:
    #         - "**"
>>>>>>> main
    workflow_dispatch:
        inputs:
            test_suite:
                description: "Run Regression Test"
                required: true
                default: "Regression"
            test_script:
                description: "loginTest"
                required: true
                default: "Bai22.Bai22_DatePickerTest"
    schedule:
        - cron: "0 2 * * *"

jobs:
    test-ci:
        name: Test CI
        timeout-minutes: 30
        runs-on: ubuntu-latest
        permissions:
            contents: "read"
            id-token: "write"
        steps:
            - uses: actions/checkout@v3

            - name: Set up JDK
              uses: actions/setup-java@v2
              with:
                  distribution: "temurin"
                  java-version: "11"

            - name: Set up Maven
              run: sudo apt-get install -y maven

            - name: Install Chrome
              run: sudo apt-get update && sudo apt-get --only-upgrade install google-chrome-stable

            - name: CI test
              run: mvn clean test -Denv=${{github.event.inputs.env}}

            - uses: actions/upload-artifact@v4
              with:
                  name: report-${{github.run_number}}
                  path: target/surefire-reports
